eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka:
      value: true
    fetch-registry:
      value: true
    instance:
      hostname: localhost

spring:
  application:
    name: api_gateway
  cloud:
    gateway:
      routes:
        - id: RegisterService
          uri: lb://RegisterService
          predicates:
            - Path=/api/v1/registry/**

        - id: LoginService
          uri: lb://LoginService
          predicates:
            - Path=/api/v1/login/**
